[package]
name = "pamm_cli"
version = "3.0.0"
edition = "2024"

[dependencies]
pamm_lib = { path = "../lib" }
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.95"
dialoguer = "0.12.0"
url = "2.5.7"
indicatif = "0.18.3"